version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000  # Correct location
    volumes:
      - ".:/code"
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres:14
    volumes: 
      - postgres_data:/var/lib/postgres/data/
    environment: 
      - "POSTGRES_HOST_AUTH_METHOD=trust"      



volumes:
  postgres_data: